[versions]
agp = "9.0.0"
androidxActivity = "1.12.3"
androidxCore = "1.17.0"
androidxLifecycle = "2.10.0"
androidxTest = "1.3.0"
junit = "4.13.2"
espressoCore = "3.6.1"
kotlin = "2.3.0"
ksp = "2.3.4"
androidxComposeBom = "2026.01.01"
androidxAppCompat = "1.7.1"
material = "1.12.0"
compileSdk = "35"
minSdk = "28"
targetSdk = "35"
onodatatableAndroidApplicationPluginId = "onodatatable.android.application"
onodatatableAndroidApplicationComposePluginId = "onodatatable.android.application.compose"
onodatatableAndroidLibraryPluginId = "onodatatable.android.library"
onodatatableAndroidLibraryComposePluginId = "onodatatable.android.library.compose"
desugarJdkLibs = "2.1.5"

[libraries]
android-desugarJdkLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugarJdkLibs" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-animation = { module = "androidx.compose.animation:animation" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout-android" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTest" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

# Dependencies of the included build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle-api", version.ref = "agp" }
compose-gradlePlugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }

# Plugins defined by this project
onodatatableApplication = { id = "onodatatable.android.application" }
onodatatableApplicationCompose = { id = "onodatatable.android.application.compose" }
onodatatableAndroidLibrary = { id = "onodatatable.android.library" }
onodatatableAndroidLibraryCompose = { id = "onodatatable.android.library.compose" }


